export interface SwiperConfig {
    direction?: string;
    touchEventsTarget?: string;
    initialSlide?: number;
    speed?: number;
    autoplay?: boolean;
    autoplayDisableOnInteraction?: boolean;
    autoplayStopOnLast?: boolean;
    iOSEdgeSwipeDetection?: boolean;
    iOSEdgeSwipeThreshold?: number;   
    freeMode?: boolean;
    freeModeMomentum?: boolean;
    freeModeMomentumRatio?: number;
    freeModeMomentumBounce?: boolean;
    freeModeMomentumBounceRatio?: number;
    freeModeSticky?: boolean;
    freeModeMinimumVelocity?: number;    
    autoHeight?: boolean;
    setWrapperSize?: boolean;    
    virtualTranslate?: boolean;
    effect?: string;
    coverflow?: {
        rotate?: number;
        stretch?: number;
        depth?: number;
        modifier?: number;
        slideShadows ?: boolean;
    },
    flip?: {
        slideShadows ?: boolean;
        limitRotation?: boolean;
    },
    cube?: {
        slideShadows?: boolean;
        shadow?: boolean;
        shadowOffset?: number;
        shadowScale?: number;
    },
    fade?: {
        crossFade?: boolean;
    },
    parallax?: boolean;
    scrollbar?: number;
    scrollbarHide?: boolean;
    scrollbarDraggable?: boolean;
    scrollbarSnapOnRelease?: boolean;    
    keyboardControl?: boolean;
    mousewheelControl?: boolean;
    mousewheelReleaseOnEdges?: boolean;
    mousewheelInvert?: boolean;
    mousewheelForceToAxis?: boolean;
    mousewheelSensitivity?: number;
    hashnav?: boolean;
    hashnavReplaceState?: boolean;
    breakpoints?: Object;
    spaceBetween?: number;
    slidesPerView?: number;
    slidesPerColumn?: number;
    slidesPerColumnFill?: string;
    slidesPerGroup?: number;
    centeredSlides?: boolean;
    slidesOffsetBefore?: number;
    slidesOffsetAfter?: number;    
    roundLengths?: boolean;
    touchRatio?: number;
    touchAngle?: number;
    simulateTouch?: boolean;
    shortSwipes?: boolean;
    longSwipes?: boolean;
    longSwipesRatio?: number;
    longSwipesMs?: number;
    followFinger?: boolean;
    onlyExternal?: boolean;
    threshold?: number;
    touchMoveStopPropagation?: boolean;    
    uniqueNavElements?: boolean;
    pagination?: any;
    paginationElement?: string;
    paginationClickable?: boolean;
    paginationHide?: boolean;
    paginationBulletRender?: (index: number, className: string) => void;
    paginationProgressRender?:(swiper: any, currentClassName: string, totalClassName: string) => void;
    paginationFractionRender?: (swiper: any, progressbarClass: string) => void;
    paginationCustomRender?: (swiper: any, current: number, total: number) => void;
    paginationType?: string;
    resistance?: boolean;
    resistanceRatio?: number;    
    nextButton?: any;
    prevButton?: any;    
    watchSlidesProgress?: boolean;
    watchSlidesVisibility?: boolean;    
    grabCursor?: boolean;    
    preventClicks?: boolean;
    preventClicksPropagation?: boolean;
    slideToClickedSlide?: boolean;    
    lazyLoading?: boolean;
    lazyLoadingInPrevNext?: boolean;
    lazyLoadingInPrevNextAmount?: number;
    lazyLoadingOnTransitionStart?: boolean;    
    preloadImages?: boolean;
    updateOnImagesReady?: boolean;    
    loop?: boolean;
    loopAdditionalSlides?: number;
    loopedSlides?: number;    
    control?: any;
    controlInverse?: boolean;
    controlBy?: string;
    allowSwipeToPrev?: boolean;
    allowSwipeToNext?: boolean;
    swipeHandler?: any;
    noSwiping?: boolean,
    noSwipingClass?: string;
    slideClass?: string;
    slideActiveClass?: string;
    slideVisibleClass?: string;
    slideDuplicateClass?: string;
    slideNextClass?: string;
    slidePrevClass?: string;
    wrapperClass?: string;
    bulletClass?: string;
    bulletActiveClass?: string;
    buttonDisabledClass?: string;
    paginationCurrentClass?: string;
    paginationTotalClass?: string;
    paginationHiddenClass?: string;
    paginationProgressbarClass?: string;
    lazyLoadingClass?: string;
    observer?: boolean,
    observeParents?: boolean,    
    a11y?: boolean,
    prevSlideMessage?: string;
    nextSlideMessage?: string;
    firstSlideMessage?: string;
    lastSlideMessage?: string;
    paginationBulletMessage?: string;
    runCallbacksOnInit?: boolean;
    onInit?: (swiper: any) => void;
    onDestroy?: (swiper: any) => void;
    onClick?: (swiper: any, e: any) => void;
    onTap?: (swiper: any, e: any) => void;
    onDoubleTap?: (swiper: any, e: any) => void;
    onSliderMove?: (swiper: any, e: any) => void;
    onSlideChangeStart?: (swiper: any) => void;
    onSlideChangeEnd?: (swiper: any) => void;
    onTransitionStart?: (swiper: any) => void;
    onTransitionEnd?: (swiper: any) => void;
    onImagesReady?: (swiper: any) => void;
    onProgress?: (swiper: any, progress: any) => void;
    onTouchStart?: (swiper: any, e: any) => void;
    onTouchMove?: (swiper: any, e: any) => void;
    onTouchMoveOpposite?: (swiper: any, e: any) => void;
    onTouchEnd?: (swiper: any, e: any) => void;
    onReachBeginning?: (swiper: any) => void;
    onReachEnd?: (swiper: any) => void;
    onSetTransition?: (swiper: any, duration: number) => void;
    onSetTranslate?: (swiper: any, translate: any) => void;
    onAutoplayStart?: (swiper: any) => void;
    onAutoplayStop?: (swiper: any) => void;
    onLazyImageLoad?: (swiper: any, slide: any, image: any) => void;
    onLazyImageReady?: (swiper: any, slide: any, image: any) => void;
}